runtime: go122

service: backend-app

automatic_scaling:  # Optional: Configure auto-scaling
  min_instances: 1
  max_instances: 5

handlers:
  - url: /.*
    script: auto  # Use "auto" to automatically handle requests
    secure: always
